# Theme
remote_theme: pages-themes/minimal@v0.2.0

# Site basics
title: Exploring Quantum Materials at SUNY New Paltz.
description: "<br><br> Kim Reyes, Greis J. PhD<br>Assistant Professor of Physics<br>kimreyesg@newpaltz.edu"
logo: /assets/img/bonding.png

# Author info
author:
  name: Kim Reyes, Greis
  email: kimreyesg@newpaltz.edu

# Plugins
plugins:
  - jekyll-remote-theme

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

# Custom CSS
defaults:
  - scope:
      path: ""
    values:
      css: /assets/css/custom.css
